all:  
  vars:
    env: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') | default('dev', True)  }}"
    password_id: "{{ env }}_{{ inventory_hostname }}_admin"
    ansible_user: "{{ lookup('bitwarden', password_id, field='username') }}"
    ansible_host: "{{ lookup('bitwarden', password_id, field='uri') }}"
    ansible_password: "{{ lookup('bitwarden', password_id, field='password') }}"
    ansible_reset_pass: "{{ lookup('bitwarden', password_id, field='password') }}"
    ansible_become_pass: "{{ lookup('bitwarden', password_id, field='password') }}"

  children:      
    servers:
      hosts:
        s0:

    nodes:
      hosts:
        n0:

