all:  
  vars:
    deploy_environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') | default('dev', True)  }}"
    entry_id: "{{ deploy_environment }}_{{ inventory_hostname }}_admin"
    ansible_user: "{{ lookup('bitwarden', entry_id, field='username') }}"
    ansible_host: "{{ lookup('bitwarden', entry_id, field='uri') }}"
    ansible_password: "{{ lookup('bitwarden', entry_id, field='password') }}"
    ansible_become_password: "{{ ansible_password }}"

  children:      
    servers:
      hosts:
        s0:

    nodes:
      hosts:
        n0:

