- name: Changing passwords of new hosts
  hosts: all
  roles:
    - ansible-modules-bitwarden
  gather_facts: no
  tasks:

  - name: Change user password
    become: yes
    tags: [never, new, change_password]
    vars:
      tmp_password: "{{ lookup('env', 'tmp_' + entry_id) }}"
      ansible_password: "{{ tmp_password }}"
      ansible_become_password: "{{ tmp_password }}"
      ansible_reset_password: "{{ lookup('bitwarden', entry_id, field='password') }}"
    when: tmp_password != ''
    user:
      name: "{{ ansible_user }}"
      update_password: always
      password: "{{ ansible_reset_password | password_hash('sha512') }}"

