- name: Changing passwords of new hosts
  hosts: all
  roles:
    - ansible-modules-bitwarden
  gather_facts: no
  tasks:

  - name: Change user password
    become: yes
    tags: [never, new]
    vars:
      tmp_password: "{{ lookup('env', 'tmp_' + password_id) }}"
      ansible_password: "{{ tmp_password }}"
      ansible_become_pass: "{{ tmp_password }}"
    when: tmp_password != ''
    user:
      name: "{{ ansible_user }}"
      update_password: always
      password: "{{ ansible_reset_pass | password_hash('sha512') }}"


- name: Configuring new hosts 
  hosts: all
  roles:
    - ansible-modules-bitwarden
  gather_facts: yes 
  tasks:

  - name: "Checking hosts ({{ env }})" 
    tags: [checks]
    ping:

  - name: Install basic packages common to all hosts
    become: yes
    tags: [always]
    when: 
      - ansible_os_family == 'Debian'
    apt:
      pkg:
      - tmux
      - vim
      - python3
      - python3-pip
      - steghide
      - gnupg2
      - tomb
      - pass
      - xclip
      state: latest
      update_cache: yes
      autoclean: yes
      autoremove: yes


- name: Changing lid behavior of servers
  hosts: servers
  roles:
    - ansible-modules-bitwarden
  gather_facts: no
  tasks:

  - name: Disable suspend on laptop lid close
    become: yes
    tags: [never, new]
    when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] | int >= 20
    lineinfile:
      path: "/etc/systemd/logind.conf"
      state: present
      regexp: "^HandleLidSwitch="
      line: "HandleLidSwitch=ignore"
 
  - name: Restart service systemd-logind
    become: yes
    when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] | int >= 20
    tags: [never, new]
    service:
      name: systemd-logind
      state: restarted
 
