- name: Setting up local ansible 
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:

  - name: Install basic aptitude dependencies
    become: yes
    tags: [always]
    when:
      - ansible_os_family == 'Debian'
    apt:
      pkg:
      - sshpass
      - ssh
      - python3
      - python3-pip
      state: latest
      update_cache: yes

  - name: Install passlib used to change passwords
    tags: [always]
    pip:
      name: passlib
      executable: pip3

  - name: Install bitwarden client
    become: yes
    tags: [always]
    when: 
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version | int >= 20
    snap:
      name: bw

  - name: Install roles from Ansible Galaxy
    command: ansible-galaxy install -r setup_local_ansible/requirements.yaml
