all:  
  vars:
    env: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') | default('dev', True)  }}"
    password_id: "{{ env }}_{{ inventory_hostname }}_admin"
    ansible_user: "{{ lookup('bitwarden', password_id, field='username') }}"
    ansible_host: "{{ lookup('bitwarden', password_id, field='uri') }}"
    ansible_password: "{{ lookup('bitwarden', password_id, field='password') }}"
    ansible_become_pass: "{{ lookup('bitwarden', password_id, field='password') }}"
    postgres_admin_id: "{{ env }}_postgres_admin"
    postgres_admin_user: "{{ lookup('bitwarden', postgres_admin_id, field='username') }}"
    postgres_admin_pass: "{{ lookup('bitwarden', postgres_admin_id, field='password') }}"
    postgres_admin_db: "{{ lookup('bitwarden', postgres_admin_id, field='database', custom_field=true) }}"

  children:      
    servers:
      hosts:
        n0:

