- name: Changing passwords of new hosts
  hosts: all
  roles:
    - ansible-modules-bitwarden
  gather_facts: no
  tasks:

  - name: Change user password
    become: yes
    tags: [never, new]
    vars:
      tmp_password: "{{ lookup('env', 'tmp_' + password_id) }}"
      ansible_password: "{{ tmp_password }}"
      ansible_become_pass: "{{ tmp_password }}"
    when: tmp_password != ''
    user:
      name: "{{ ansible_user }}"
      update_password: always
      password: "{{ ansible_reset_pass | password_hash('sha512') }}"


- name: Configuring new hosts 
  hosts: all
  roles:
    - ansible-modules-bitwarden
  gather_facts: yes 
  tasks:

  - name: "Checking hosts ({{ env }})" 
    tags: [checks]
    ping:

  - name: Install basic packages common to all hosts
    become: yes
    tags: [always]
    when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] | int >= 20
    apt:
      pkg:
      - tmux
      - vim
      - python3
      - python3-pip
      state: latest
      update_cache: yes
      autoclean: yes
      autoremove: yes

